// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/common/grtc.proto

package common

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Routing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int32                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Routing) Reset() {
	*x = Routing{}
	mi := &file_api_common_grtc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Routing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Routing) ProtoMessage() {}

func (x *Routing) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_grtc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Routing.ProtoReflect.Descriptor instead.
func (*Routing) Descriptor() ([]byte, []int) {
	return file_api_common_grtc_proto_rawDescGZIP(), []int{0}
}

func (x *Routing) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type Request struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Routing *Routing               `protobuf:"bytes,1,opt,name=routing,proto3" json:"routing,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*Request_Call
	//	*Request_Data
	//	*Request_End
	Type          isRequest_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_api_common_grtc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_grtc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_api_common_grtc_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetRouting() *Routing {
	if x != nil {
		return x.Routing
	}
	return nil
}

func (x *Request) GetType() isRequest_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Request) GetCall() *Call {
	if x != nil {
		if x, ok := x.Type.(*Request_Call); ok {
			return x.Call
		}
	}
	return nil
}

func (x *Request) GetData() *Data {
	if x != nil {
		if x, ok := x.Type.(*Request_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Request) GetEnd() *End {
	if x != nil {
		if x, ok := x.Type.(*Request_End); ok {
			return x.End
		}
	}
	return nil
}

type isRequest_Type interface {
	isRequest_Type()
}

type Request_Call struct {
	Call *Call `protobuf:"bytes,2,opt,name=call,proto3,oneof"`
}

type Request_Data struct {
	Data *Data `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type Request_End struct {
	End *End `protobuf:"bytes,4,opt,name=end,proto3,oneof"`
}

func (*Request_Call) isRequest_Type() {}

func (*Request_Data) isRequest_Type() {}

func (*Request_End) isRequest_Type() {}

type Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Routing *Routing               `protobuf:"bytes,1,opt,name=routing,proto3" json:"routing,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*Response_Begin
	//	*Response_Data
	//	*Response_End
	Type          isResponse_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_common_grtc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_grtc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_common_grtc_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetRouting() *Routing {
	if x != nil {
		return x.Routing
	}
	return nil
}

func (x *Response) GetType() isResponse_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Response) GetBegin() *Begin {
	if x != nil {
		if x, ok := x.Type.(*Response_Begin); ok {
			return x.Begin
		}
	}
	return nil
}

func (x *Response) GetData() *Data {
	if x != nil {
		if x, ok := x.Type.(*Response_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Response) GetEnd() *End {
	if x != nil {
		if x, ok := x.Type.(*Response_End); ok {
			return x.End
		}
	}
	return nil
}

type isResponse_Type interface {
	isResponse_Type()
}

type Response_Begin struct {
	Begin *Begin `protobuf:"bytes,2,opt,name=begin,proto3,oneof"`
}

type Response_Data struct {
	Data *Data `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type Response_End struct {
	End *End `protobuf:"bytes,4,opt,name=end,proto3,oneof"`
}

func (*Response_Begin) isResponse_Type() {}

func (*Response_Data) isResponse_Type() {}

func (*Response_End) isResponse_Type() {}

type Strings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Strings) Reset() {
	*x = Strings{}
	mi := &file_api_common_grtc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Strings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strings) ProtoMessage() {}

func (x *Strings) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_grtc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strings.ProtoReflect.Descriptor instead.
func (*Strings) Descriptor() ([]byte, []int) {
	return file_api_common_grtc_proto_rawDescGZIP(), []int{3}
}

func (x *Strings) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Md            map[string]*Strings    `protobuf:"bytes,1,rep,name=md,proto3" json:"md,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_api_common_grtc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_grtc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_api_common_grtc_proto_rawDescGZIP(), []int{4}
}

func (x *Metadata) GetMd() map[string]*Strings {
	if x != nil {
		return x.Md
	}
	return nil
}

type Call struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"` // TODO: deadline
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Call) Reset() {
	*x = Call{}
	mi := &file_api_common_grtc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_grtc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_api_common_grtc_proto_rawDescGZIP(), []int{5}
}

func (x *Call) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Call) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Begin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Metadata              `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Begin) Reset() {
	*x = Begin{}
	mi := &file_api_common_grtc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Begin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Begin) ProtoMessage() {}

func (x *Begin) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_grtc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Begin.ProtoReflect.Descriptor instead.
func (*Begin) Descriptor() ([]byte, []int) {
	return file_api_common_grtc_proto_rawDescGZIP(), []int{6}
}

func (x *Begin) GetHeader() *Metadata {
	if x != nil {
		return x.Header
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_api_common_grtc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_grtc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_api_common_grtc_proto_rawDescGZIP(), []int{7}
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type End struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *status.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Trailer       *Metadata              `protobuf:"bytes,2,opt,name=trailer,proto3" json:"trailer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *End) Reset() {
	*x = End{}
	mi := &file_api_common_grtc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *End) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*End) ProtoMessage() {}

func (x *End) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_grtc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use End.ProtoReflect.Descriptor instead.
func (*End) Descriptor() ([]byte, []int) {
	return file_api_common_grtc_proto_rawDescGZIP(), []int{8}
}

func (x *End) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *End) GetTrailer() *Metadata {
	if x != nil {
		return x.Trailer
	}
	return nil
}

var File_api_common_grtc_proto protoreflect.FileDescriptor

const file_api_common_grtc_proto_rawDesc = "" +
	"\n" +
	"\x15api/common/grtc.proto\x12\x04grtc\x1a\x17google/rpc/status.proto\"%\n" +
	"\aRouting\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x05R\bsequence\"\x9d\x01\n" +
	"\aRequest\x12'\n" +
	"\arouting\x18\x01 \x01(\v2\r.grtc.RoutingR\arouting\x12 \n" +
	"\x04call\x18\x02 \x01(\v2\n" +
	".grtc.CallH\x00R\x04call\x12 \n" +
	"\x04data\x18\x03 \x01(\v2\n" +
	".grtc.DataH\x00R\x04data\x12\x1d\n" +
	"\x03end\x18\x04 \x01(\v2\t.grtc.EndH\x00R\x03endB\x06\n" +
	"\x04type\"\xa1\x01\n" +
	"\bResponse\x12'\n" +
	"\arouting\x18\x01 \x01(\v2\r.grtc.RoutingR\arouting\x12#\n" +
	"\x05begin\x18\x02 \x01(\v2\v.grtc.BeginH\x00R\x05begin\x12 \n" +
	"\x04data\x18\x03 \x01(\v2\n" +
	".grtc.DataH\x00R\x04data\x12\x1d\n" +
	"\x03end\x18\x04 \x01(\v2\t.grtc.EndH\x00R\x03endB\x06\n" +
	"\x04type\"!\n" +
	"\aStrings\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"x\n" +
	"\bMetadata\x12&\n" +
	"\x02md\x18\x01 \x03(\v2\x16.grtc.Metadata.MdEntryR\x02md\x1aD\n" +
	"\aMdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.grtc.StringsR\x05value:\x028\x01\"J\n" +
	"\x04Call\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12*\n" +
	"\bmetadata\x18\x02 \x01(\v2\x0e.grtc.MetadataR\bmetadata\"/\n" +
	"\x05Begin\x12&\n" +
	"\x06header\x18\x01 \x01(\v2\x0e.grtc.MetadataR\x06header\"\x1a\n" +
	"\x04Data\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"[\n" +
	"\x03End\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\x12(\n" +
	"\atrailer\x18\x02 \x01(\v2\x0e.grtc.MetadataR\atrailerB\x11Z\x0f../proto/commonb\x06proto3"

var (
	file_api_common_grtc_proto_rawDescOnce sync.Once
	file_api_common_grtc_proto_rawDescData []byte
)

func file_api_common_grtc_proto_rawDescGZIP() []byte {
	file_api_common_grtc_proto_rawDescOnce.Do(func() {
		file_api_common_grtc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_grtc_proto_rawDesc), len(file_api_common_grtc_proto_rawDesc)))
	})
	return file_api_common_grtc_proto_rawDescData
}

var file_api_common_grtc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_common_grtc_proto_goTypes = []any{
	(*Routing)(nil),       // 0: grtc.Routing
	(*Request)(nil),       // 1: grtc.Request
	(*Response)(nil),      // 2: grtc.Response
	(*Strings)(nil),       // 3: grtc.Strings
	(*Metadata)(nil),      // 4: grtc.Metadata
	(*Call)(nil),          // 5: grtc.Call
	(*Begin)(nil),         // 6: grtc.Begin
	(*Data)(nil),          // 7: grtc.Data
	(*End)(nil),           // 8: grtc.End
	nil,                   // 9: grtc.Metadata.MdEntry
	(*status.Status)(nil), // 10: google.rpc.Status
}
var file_api_common_grtc_proto_depIdxs = []int32{
	0,  // 0: grtc.Request.routing:type_name -> grtc.Routing
	5,  // 1: grtc.Request.call:type_name -> grtc.Call
	7,  // 2: grtc.Request.data:type_name -> grtc.Data
	8,  // 3: grtc.Request.end:type_name -> grtc.End
	0,  // 4: grtc.Response.routing:type_name -> grtc.Routing
	6,  // 5: grtc.Response.begin:type_name -> grtc.Begin
	7,  // 6: grtc.Response.data:type_name -> grtc.Data
	8,  // 7: grtc.Response.end:type_name -> grtc.End
	9,  // 8: grtc.Metadata.md:type_name -> grtc.Metadata.MdEntry
	4,  // 9: grtc.Call.metadata:type_name -> grtc.Metadata
	4,  // 10: grtc.Begin.header:type_name -> grtc.Metadata
	10, // 11: grtc.End.status:type_name -> google.rpc.Status
	4,  // 12: grtc.End.trailer:type_name -> grtc.Metadata
	3,  // 13: grtc.Metadata.MdEntry.value:type_name -> grtc.Strings
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_common_grtc_proto_init() }
func file_api_common_grtc_proto_init() {
	if File_api_common_grtc_proto != nil {
		return
	}
	file_api_common_grtc_proto_msgTypes[1].OneofWrappers = []any{
		(*Request_Call)(nil),
		(*Request_Data)(nil),
		(*Request_End)(nil),
	}
	file_api_common_grtc_proto_msgTypes[2].OneofWrappers = []any{
		(*Response_Begin)(nil),
		(*Response_Data)(nil),
		(*Response_End)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_grtc_proto_rawDesc), len(file_api_common_grtc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_grtc_proto_goTypes,
		DependencyIndexes: file_api_common_grtc_proto_depIdxs,
		MessageInfos:      file_api_common_grtc_proto_msgTypes,
	}.Build()
	File_api_common_grtc_proto = out.File
	file_api_common_grtc_proto_goTypes = nil
	file_api_common_grtc_proto_depIdxs = nil
}
