// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/v1/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ManagedAccount represents credentials for an external app
type ManagedAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   string                 `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	SigninUrl     string                 `protobuf:"bytes,4,opt,name=signin_url,json=signinUrl,proto3" json:"signin_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedAccount) Reset() {
	*x = ManagedAccount{}
	mi := &file_api_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedAccount) ProtoMessage() {}

func (x *ManagedAccount) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedAccount.ProtoReflect.Descriptor instead.
func (*ManagedAccount) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *ManagedAccount) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *ManagedAccount) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ManagedAccount) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ManagedAccount) GetSigninUrl() string {
	if x != nil {
		return x.SigninUrl
	}
	return ""
}

// Main User message mirroring the Go struct (simplified for gRPC)
type User struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Owner             string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedTime       string                 `protobuf:"bytes,3,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime       string                 `protobuf:"bytes,4,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	Id                string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId        string                 `protobuf:"bytes,6,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Type              string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Password          string                 `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	PasswordSalt      string                 `protobuf:"bytes,9,opt,name=password_salt,json=passwordSalt,proto3" json:"password_salt,omitempty"`
	PasswordType      string                 `protobuf:"bytes,10,opt,name=password_type,json=passwordType,proto3" json:"password_type,omitempty"`
	DisplayName       string                 `protobuf:"bytes,11,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	FirstName         string                 `protobuf:"bytes,12,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName          string                 `protobuf:"bytes,13,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Avatar            string                 `protobuf:"bytes,14,opt,name=avatar,proto3" json:"avatar,omitempty"`
	AvatarType        string                 `protobuf:"bytes,15,opt,name=avatar_type,json=avatarType,proto3" json:"avatar_type,omitempty"`
	PermanentAvatar   string                 `protobuf:"bytes,16,opt,name=permanent_avatar,json=permanentAvatar,proto3" json:"permanent_avatar,omitempty"`
	Email             string                 `protobuf:"bytes,17,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified     bool                   `protobuf:"varint,18,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	Phone             string                 `protobuf:"bytes,19,opt,name=phone,proto3" json:"phone,omitempty"`
	CountryCode       string                 `protobuf:"bytes,20,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Region            string                 `protobuf:"bytes,21,opt,name=region,proto3" json:"region,omitempty"`
	Location          string                 `protobuf:"bytes,22,opt,name=location,proto3" json:"location,omitempty"`
	Address           []string               `protobuf:"bytes,23,rep,name=address,proto3" json:"address,omitempty"`
	Affiliation       string                 `protobuf:"bytes,24,opt,name=affiliation,proto3" json:"affiliation,omitempty"`
	Title             string                 `protobuf:"bytes,25,opt,name=title,proto3" json:"title,omitempty"`
	IdCardType        string                 `protobuf:"bytes,26,opt,name=id_card_type,json=idCardType,proto3" json:"id_card_type,omitempty"`
	IdCard            string                 `protobuf:"bytes,27,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	Homepage          string                 `protobuf:"bytes,28,opt,name=homepage,proto3" json:"homepage,omitempty"`
	Bio               string                 `protobuf:"bytes,29,opt,name=bio,proto3" json:"bio,omitempty"`
	Tag               string                 `protobuf:"bytes,30,opt,name=tag,proto3" json:"tag,omitempty"`
	Language          string                 `protobuf:"bytes,31,opt,name=language,proto3" json:"language,omitempty"`
	Gender            string                 `protobuf:"bytes,32,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday          string                 `protobuf:"bytes,33,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Education         string                 `protobuf:"bytes,34,opt,name=education,proto3" json:"education,omitempty"`
	Score             int32                  `protobuf:"varint,35,opt,name=score,proto3" json:"score,omitempty"`
	Karma             int32                  `protobuf:"varint,36,opt,name=karma,proto3" json:"karma,omitempty"`
	Ranking           int32                  `protobuf:"varint,37,opt,name=ranking,proto3" json:"ranking,omitempty"`
	IsDefaultAvatar   bool                   `protobuf:"varint,38,opt,name=is_default_avatar,json=isDefaultAvatar,proto3" json:"is_default_avatar,omitempty"`
	IsOnline          bool                   `protobuf:"varint,39,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	IsAdmin           bool                   `protobuf:"varint,40,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	IsForbidden       bool                   `protobuf:"varint,41,opt,name=is_forbidden,json=isForbidden,proto3" json:"is_forbidden,omitempty"`
	IsDeleted         bool                   `protobuf:"varint,42,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	SignupApplication string                 `protobuf:"bytes,43,opt,name=signup_application,json=signupApplication,proto3" json:"signup_application,omitempty"`
	Hash              string                 `protobuf:"bytes,44,opt,name=hash,proto3" json:"hash,omitempty"`
	PreHash           string                 `protobuf:"bytes,45,opt,name=pre_hash,json=preHash,proto3" json:"pre_hash,omitempty"`
	AccessKey         string                 `protobuf:"bytes,46,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	AccessSecret      string                 `protobuf:"bytes,47,opt,name=access_secret,json=accessSecret,proto3" json:"access_secret,omitempty"`
	CreatedIp         string                 `protobuf:"bytes,48,opt,name=created_ip,json=createdIp,proto3" json:"created_ip,omitempty"`
	LastSigninTime    string                 `protobuf:"bytes,49,opt,name=last_signin_time,json=lastSigninTime,proto3" json:"last_signin_time,omitempty"`
	LastSigninIp      string                 `protobuf:"bytes,50,opt,name=last_signin_ip,json=lastSigninIp,proto3" json:"last_signin_ip,omitempty"`
	// Social logins (only a few shown for brevity; you can add more if needed)
	Github                 string            `protobuf:"bytes,51,opt,name=github,proto3" json:"github,omitempty"`
	Google                 string            `protobuf:"bytes,52,opt,name=google,proto3" json:"google,omitempty"`
	Qq                     string            `protobuf:"bytes,53,opt,name=qq,proto3" json:"qq,omitempty"`
	Wechat                 string            `protobuf:"bytes,54,opt,name=wechat,proto3" json:"wechat,omitempty"`
	Facebook               string            `protobuf:"bytes,55,opt,name=facebook,proto3" json:"facebook,omitempty"`
	Dingtalk               string            `protobuf:"bytes,56,opt,name=dingtalk,proto3" json:"dingtalk,omitempty"`
	Weibo                  string            `protobuf:"bytes,57,opt,name=weibo,proto3" json:"weibo,omitempty"`
	Gitee                  string            `protobuf:"bytes,58,opt,name=gitee,proto3" json:"gitee,omitempty"`
	Linkedin               string            `protobuf:"bytes,59,opt,name=linkedin,proto3" json:"linkedin,omitempty"`
	Wecom                  string            `protobuf:"bytes,60,opt,name=wecom,proto3" json:"wecom,omitempty"`
	Lark                   string            `protobuf:"bytes,61,opt,name=lark,proto3" json:"lark,omitempty"`
	Gitlab                 string            `protobuf:"bytes,62,opt,name=gitlab,proto3" json:"gitlab,omitempty"`
	Adfs                   string            `protobuf:"bytes,63,opt,name=adfs,proto3" json:"adfs,omitempty"`
	Baidu                  string            `protobuf:"bytes,64,opt,name=baidu,proto3" json:"baidu,omitempty"`
	Alipay                 string            `protobuf:"bytes,65,opt,name=alipay,proto3" json:"alipay,omitempty"`
	Casdoor                string            `protobuf:"bytes,66,opt,name=casdoor,proto3" json:"casdoor,omitempty"`
	PreferredMfaType       string            `protobuf:"bytes,67,opt,name=preferred_mfa_type,json=preferredMfaType,proto3" json:"preferred_mfa_type,omitempty"`
	RecoveryCodes          []string          `protobuf:"bytes,68,rep,name=recovery_codes,json=recoveryCodes,proto3" json:"recovery_codes,omitempty"`
	TotpSecret             string            `protobuf:"bytes,69,opt,name=totp_secret,json=totpSecret,proto3" json:"totp_secret,omitempty"`
	MfaPhoneEnabled        bool              `protobuf:"varint,70,opt,name=mfa_phone_enabled,json=mfaPhoneEnabled,proto3" json:"mfa_phone_enabled,omitempty"`
	MfaEmailEnabled        bool              `protobuf:"varint,71,opt,name=mfa_email_enabled,json=mfaEmailEnabled,proto3" json:"mfa_email_enabled,omitempty"`
	Invitation             string            `protobuf:"bytes,72,opt,name=invitation,proto3" json:"invitation,omitempty"`
	InvitationCode         string            `protobuf:"bytes,73,opt,name=invitation_code,json=invitationCode,proto3" json:"invitation_code,omitempty"`
	Ldap                   string            `protobuf:"bytes,74,opt,name=ldap,proto3" json:"ldap,omitempty"`
	Properties             map[string]string `protobuf:"bytes,75,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Groups                 []string          `protobuf:"bytes,76,rep,name=groups,proto3" json:"groups,omitempty"`
	LastChangePasswordTime string            `protobuf:"bytes,77,opt,name=last_change_password_time,json=lastChangePasswordTime,proto3" json:"last_change_password_time,omitempty"`
	LastSigninWrongTime    string            `protobuf:"bytes,78,opt,name=last_signin_wrong_time,json=lastSigninWrongTime,proto3" json:"last_signin_wrong_time,omitempty"`
	SigninWrongTimes       int32             `protobuf:"varint,79,opt,name=signin_wrong_times,json=signinWrongTimes,proto3" json:"signin_wrong_times,omitempty"`
	ManagedAccounts        []*ManagedAccount `protobuf:"bytes,80,rep,name=managed_accounts,json=managedAccounts,proto3" json:"managed_accounts,omitempty"`
	NeedUpdatePassword     bool              `protobuf:"varint,81,opt,name=need_update_password,json=needUpdatePassword,proto3" json:"need_update_password,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *User) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *User) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetPasswordSalt() string {
	if x != nil {
		return x.PasswordSalt
	}
	return ""
}

func (x *User) GetPasswordType() string {
	if x != nil {
		return x.PasswordType
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetAvatarType() string {
	if x != nil {
		return x.AvatarType
	}
	return ""
}

func (x *User) GetPermanentAvatar() string {
	if x != nil {
		return x.PermanentAvatar
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *User) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *User) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *User) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *User) GetAffiliation() string {
	if x != nil {
		return x.Affiliation
	}
	return ""
}

func (x *User) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *User) GetIdCardType() string {
	if x != nil {
		return x.IdCardType
	}
	return ""
}

func (x *User) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *User) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *User) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *User) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *User) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *User) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *User) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *User) GetKarma() int32 {
	if x != nil {
		return x.Karma
	}
	return 0
}

func (x *User) GetRanking() int32 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

func (x *User) GetIsDefaultAvatar() bool {
	if x != nil {
		return x.IsDefaultAvatar
	}
	return false
}

func (x *User) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *User) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *User) GetIsForbidden() bool {
	if x != nil {
		return x.IsForbidden
	}
	return false
}

func (x *User) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *User) GetSignupApplication() string {
	if x != nil {
		return x.SignupApplication
	}
	return ""
}

func (x *User) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *User) GetPreHash() string {
	if x != nil {
		return x.PreHash
	}
	return ""
}

func (x *User) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *User) GetAccessSecret() string {
	if x != nil {
		return x.AccessSecret
	}
	return ""
}

func (x *User) GetCreatedIp() string {
	if x != nil {
		return x.CreatedIp
	}
	return ""
}

func (x *User) GetLastSigninTime() string {
	if x != nil {
		return x.LastSigninTime
	}
	return ""
}

func (x *User) GetLastSigninIp() string {
	if x != nil {
		return x.LastSigninIp
	}
	return ""
}

func (x *User) GetGithub() string {
	if x != nil {
		return x.Github
	}
	return ""
}

func (x *User) GetGoogle() string {
	if x != nil {
		return x.Google
	}
	return ""
}

func (x *User) GetQq() string {
	if x != nil {
		return x.Qq
	}
	return ""
}

func (x *User) GetWechat() string {
	if x != nil {
		return x.Wechat
	}
	return ""
}

func (x *User) GetFacebook() string {
	if x != nil {
		return x.Facebook
	}
	return ""
}

func (x *User) GetDingtalk() string {
	if x != nil {
		return x.Dingtalk
	}
	return ""
}

func (x *User) GetWeibo() string {
	if x != nil {
		return x.Weibo
	}
	return ""
}

func (x *User) GetGitee() string {
	if x != nil {
		return x.Gitee
	}
	return ""
}

func (x *User) GetLinkedin() string {
	if x != nil {
		return x.Linkedin
	}
	return ""
}

func (x *User) GetWecom() string {
	if x != nil {
		return x.Wecom
	}
	return ""
}

func (x *User) GetLark() string {
	if x != nil {
		return x.Lark
	}
	return ""
}

func (x *User) GetGitlab() string {
	if x != nil {
		return x.Gitlab
	}
	return ""
}

func (x *User) GetAdfs() string {
	if x != nil {
		return x.Adfs
	}
	return ""
}

func (x *User) GetBaidu() string {
	if x != nil {
		return x.Baidu
	}
	return ""
}

func (x *User) GetAlipay() string {
	if x != nil {
		return x.Alipay
	}
	return ""
}

func (x *User) GetCasdoor() string {
	if x != nil {
		return x.Casdoor
	}
	return ""
}

func (x *User) GetPreferredMfaType() string {
	if x != nil {
		return x.PreferredMfaType
	}
	return ""
}

func (x *User) GetRecoveryCodes() []string {
	if x != nil {
		return x.RecoveryCodes
	}
	return nil
}

func (x *User) GetTotpSecret() string {
	if x != nil {
		return x.TotpSecret
	}
	return ""
}

func (x *User) GetMfaPhoneEnabled() bool {
	if x != nil {
		return x.MfaPhoneEnabled
	}
	return false
}

func (x *User) GetMfaEmailEnabled() bool {
	if x != nil {
		return x.MfaEmailEnabled
	}
	return false
}

func (x *User) GetInvitation() string {
	if x != nil {
		return x.Invitation
	}
	return ""
}

func (x *User) GetInvitationCode() string {
	if x != nil {
		return x.InvitationCode
	}
	return ""
}

func (x *User) GetLdap() string {
	if x != nil {
		return x.Ldap
	}
	return ""
}

func (x *User) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *User) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *User) GetLastChangePasswordTime() string {
	if x != nil {
		return x.LastChangePasswordTime
	}
	return ""
}

func (x *User) GetLastSigninWrongTime() string {
	if x != nil {
		return x.LastSigninWrongTime
	}
	return ""
}

func (x *User) GetSigninWrongTimes() int32 {
	if x != nil {
		return x.SigninWrongTimes
	}
	return 0
}

func (x *User) GetManagedAccounts() []*ManagedAccount {
	if x != nil {
		return x.ManagedAccounts
	}
	return nil
}

func (x *User) GetNeedUpdatePassword() bool {
	if x != nil {
		return x.NeedUpdatePassword
	}
	return false
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // format: "owner/name"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmailRequest) Reset() {
	*x = GetUserByEmailRequest{}
	mi := &file_api_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmailRequest) ProtoMessage() {}

func (x *GetUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByEmailRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserByPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByPhoneRequest) Reset() {
	*x = GetUserByPhoneRequest{}
	mi := &file_api_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByPhoneRequest) ProtoMessage() {}

func (x *GetUserByPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByPhoneRequest.ProtoReflect.Descriptor instead.
func (*GetUserByPhoneRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByPhoneRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetUserByPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetUserByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByUserIdRequest) Reset() {
	*x = GetUserByUserIdRequest{}
	mi := &file_api_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUserIdRequest) ProtoMessage() {}

func (x *GetUserByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserByUserIdRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetUserByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_api_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUsersRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type GetSortedUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Sorter        string                 `protobuf:"bytes,2,opt,name=sorter,proto3" json:"sorter,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSortedUsersRequest) Reset() {
	*x = GetSortedUsersRequest{}
	mi := &file_api_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSortedUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSortedUsersRequest) ProtoMessage() {}

func (x *GetSortedUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSortedUsersRequest.ProtoReflect.Descriptor instead.
func (*GetSortedUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetSortedUsersRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetSortedUsersRequest) GetSorter() string {
	if x != nil {
		return x.Sorter
	}
	return ""
}

func (x *GetSortedUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetPaginationUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Query         map[string]string      `protobuf:"bytes,4,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // additional filters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaginationUsersRequest) Reset() {
	*x = GetPaginationUsersRequest{}
	mi := &file_api_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaginationUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaginationUsersRequest) ProtoMessage() {}

func (x *GetPaginationUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaginationUsersRequest.ProtoReflect.Descriptor instead.
func (*GetPaginationUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetPaginationUsersRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetPaginationUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPaginationUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetPaginationUsersRequest) GetQuery() map[string]string {
	if x != nil {
		return x.Query
	}
	return nil
}

type GetUserCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	IsOnline      string                 `protobuf:"bytes,2,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"` // "true", "false", or ""
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCountRequest) Reset() {
	*x = GetUserCountRequest{}
	mi := &file_api_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCountRequest) ProtoMessage() {}

func (x *GetUserCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCountRequest.ProtoReflect.Descriptor instead.
func (*GetUserCountRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserCountRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetUserCountRequest) GetIsOnline() string {
	if x != nil {
		return x.IsOnline
	}
	return ""
}

type SetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserOwner     string                 `protobuf:"bytes,1,opt,name=user_owner,json=userOwner,proto3" json:"user_owner,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	OldPassword   string                 `protobuf:"bytes,3,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,4,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPasswordRequest) Reset() {
	*x = SetPasswordRequest{}
	mi := &file_api_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPasswordRequest) ProtoMessage() {}

func (x *SetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPasswordRequest.ProtoReflect.Descriptor instead.
func (*SetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *SetPasswordRequest) GetUserOwner() string {
	if x != nil {
		return x.UserOwner
	}
	return ""
}

func (x *SetPasswordRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SetPasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *SetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type AddUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	mi := &file_api_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *AddUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Columns       []string               `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"` // optional: if partial update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserRequest) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_api_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CheckUserPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserPasswordRequest) Reset() {
	*x = CheckUserPasswordRequest{}
	mi := &file_api_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserPasswordRequest) ProtoMessage() {}

func (x *CheckUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*CheckUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *CheckUserPasswordRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Generic response
type BoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolResponse) Reset() {
	*x = BoolResponse{}
	mi := &file_api_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolResponse) ProtoMessage() {}

func (x *BoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolResponse.ProtoReflect.Descriptor instead.
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *BoolResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_api_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{16}
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersResponse) Reset() {
	*x = UsersResponse{}
	mi := &file_api_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersResponse) ProtoMessage() {}

func (x *UsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersResponse.ProtoReflect.Descriptor instead.
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{17}
}

func (x *UsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type PaginatedUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginatedUsersResponse) Reset() {
	*x = PaginatedUsersResponse{}
	mi := &file_api_v1_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginatedUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatedUsersResponse) ProtoMessage() {}

func (x *PaginatedUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatedUsersResponse.ProtoReflect.Descriptor instead.
func (*PaginatedUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{18}
}

func (x *PaginatedUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *PaginatedUsersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_api_v1_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{19}
}

func (x *CountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_v1_user_proto protoreflect.FileDescriptor

const file_api_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/user.proto\x12\x06api.v1\"\x89\x01\n" +
	"\x0eManagedAccount\x12 \n" +
	"\vapplication\x18\x01 \x01(\tR\vapplication\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"signin_url\x18\x04 \x01(\tR\tsigninUrl\"\x8f\x14\n" +
	"\x04User\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fcreated_time\x18\x03 \x01(\tR\vcreatedTime\x12!\n" +
	"\fupdated_time\x18\x04 \x01(\tR\vupdatedTime\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x06 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1a\n" +
	"\bpassword\x18\b \x01(\tR\bpassword\x12#\n" +
	"\rpassword_salt\x18\t \x01(\tR\fpasswordSalt\x12#\n" +
	"\rpassword_type\x18\n" +
	" \x01(\tR\fpasswordType\x12!\n" +
	"\fdisplay_name\x18\v \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"first_name\x18\f \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\r \x01(\tR\blastName\x12\x16\n" +
	"\x06avatar\x18\x0e \x01(\tR\x06avatar\x12\x1f\n" +
	"\vavatar_type\x18\x0f \x01(\tR\n" +
	"avatarType\x12)\n" +
	"\x10permanent_avatar\x18\x10 \x01(\tR\x0fpermanentAvatar\x12\x14\n" +
	"\x05email\x18\x11 \x01(\tR\x05email\x12%\n" +
	"\x0eemail_verified\x18\x12 \x01(\bR\remailVerified\x12\x14\n" +
	"\x05phone\x18\x13 \x01(\tR\x05phone\x12!\n" +
	"\fcountry_code\x18\x14 \x01(\tR\vcountryCode\x12\x16\n" +
	"\x06region\x18\x15 \x01(\tR\x06region\x12\x1a\n" +
	"\blocation\x18\x16 \x01(\tR\blocation\x12\x18\n" +
	"\aaddress\x18\x17 \x03(\tR\aaddress\x12 \n" +
	"\vaffiliation\x18\x18 \x01(\tR\vaffiliation\x12\x14\n" +
	"\x05title\x18\x19 \x01(\tR\x05title\x12 \n" +
	"\fid_card_type\x18\x1a \x01(\tR\n" +
	"idCardType\x12\x17\n" +
	"\aid_card\x18\x1b \x01(\tR\x06idCard\x12\x1a\n" +
	"\bhomepage\x18\x1c \x01(\tR\bhomepage\x12\x10\n" +
	"\x03bio\x18\x1d \x01(\tR\x03bio\x12\x10\n" +
	"\x03tag\x18\x1e \x01(\tR\x03tag\x12\x1a\n" +
	"\blanguage\x18\x1f \x01(\tR\blanguage\x12\x16\n" +
	"\x06gender\x18  \x01(\tR\x06gender\x12\x1a\n" +
	"\bbirthday\x18! \x01(\tR\bbirthday\x12\x1c\n" +
	"\teducation\x18\" \x01(\tR\teducation\x12\x14\n" +
	"\x05score\x18# \x01(\x05R\x05score\x12\x14\n" +
	"\x05karma\x18$ \x01(\x05R\x05karma\x12\x18\n" +
	"\aranking\x18% \x01(\x05R\aranking\x12*\n" +
	"\x11is_default_avatar\x18& \x01(\bR\x0fisDefaultAvatar\x12\x1b\n" +
	"\tis_online\x18' \x01(\bR\bisOnline\x12\x19\n" +
	"\bis_admin\x18( \x01(\bR\aisAdmin\x12!\n" +
	"\fis_forbidden\x18) \x01(\bR\visForbidden\x12\x1d\n" +
	"\n" +
	"is_deleted\x18* \x01(\bR\tisDeleted\x12-\n" +
	"\x12signup_application\x18+ \x01(\tR\x11signupApplication\x12\x12\n" +
	"\x04hash\x18, \x01(\tR\x04hash\x12\x19\n" +
	"\bpre_hash\x18- \x01(\tR\apreHash\x12\x1d\n" +
	"\n" +
	"access_key\x18. \x01(\tR\taccessKey\x12#\n" +
	"\raccess_secret\x18/ \x01(\tR\faccessSecret\x12\x1d\n" +
	"\n" +
	"created_ip\x180 \x01(\tR\tcreatedIp\x12(\n" +
	"\x10last_signin_time\x181 \x01(\tR\x0elastSigninTime\x12$\n" +
	"\x0elast_signin_ip\x182 \x01(\tR\flastSigninIp\x12\x16\n" +
	"\x06github\x183 \x01(\tR\x06github\x12\x16\n" +
	"\x06google\x184 \x01(\tR\x06google\x12\x0e\n" +
	"\x02qq\x185 \x01(\tR\x02qq\x12\x16\n" +
	"\x06wechat\x186 \x01(\tR\x06wechat\x12\x1a\n" +
	"\bfacebook\x187 \x01(\tR\bfacebook\x12\x1a\n" +
	"\bdingtalk\x188 \x01(\tR\bdingtalk\x12\x14\n" +
	"\x05weibo\x189 \x01(\tR\x05weibo\x12\x14\n" +
	"\x05gitee\x18: \x01(\tR\x05gitee\x12\x1a\n" +
	"\blinkedin\x18; \x01(\tR\blinkedin\x12\x14\n" +
	"\x05wecom\x18< \x01(\tR\x05wecom\x12\x12\n" +
	"\x04lark\x18= \x01(\tR\x04lark\x12\x16\n" +
	"\x06gitlab\x18> \x01(\tR\x06gitlab\x12\x12\n" +
	"\x04adfs\x18? \x01(\tR\x04adfs\x12\x14\n" +
	"\x05baidu\x18@ \x01(\tR\x05baidu\x12\x16\n" +
	"\x06alipay\x18A \x01(\tR\x06alipay\x12\x18\n" +
	"\acasdoor\x18B \x01(\tR\acasdoor\x12,\n" +
	"\x12preferred_mfa_type\x18C \x01(\tR\x10preferredMfaType\x12%\n" +
	"\x0erecovery_codes\x18D \x03(\tR\rrecoveryCodes\x12\x1f\n" +
	"\vtotp_secret\x18E \x01(\tR\n" +
	"totpSecret\x12*\n" +
	"\x11mfa_phone_enabled\x18F \x01(\bR\x0fmfaPhoneEnabled\x12*\n" +
	"\x11mfa_email_enabled\x18G \x01(\bR\x0fmfaEmailEnabled\x12\x1e\n" +
	"\n" +
	"invitation\x18H \x01(\tR\n" +
	"invitation\x12'\n" +
	"\x0finvitation_code\x18I \x01(\tR\x0einvitationCode\x12\x12\n" +
	"\x04ldap\x18J \x01(\tR\x04ldap\x12<\n" +
	"\n" +
	"properties\x18K \x03(\v2\x1c.api.v1.User.PropertiesEntryR\n" +
	"properties\x12\x16\n" +
	"\x06groups\x18L \x03(\tR\x06groups\x129\n" +
	"\x19last_change_password_time\x18M \x01(\tR\x16lastChangePasswordTime\x123\n" +
	"\x16last_signin_wrong_time\x18N \x01(\tR\x13lastSigninWrongTime\x12,\n" +
	"\x12signin_wrong_times\x18O \x01(\x05R\x10signinWrongTimes\x12A\n" +
	"\x10managed_accounts\x18P \x03(\v2\x16.api.v1.ManagedAccountR\x0fmanagedAccounts\x120\n" +
	"\x14need_update_password\x18Q \x01(\bR\x12needUpdatePassword\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x15GetUserByEmailRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"C\n" +
	"\x15GetUserByPhoneRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"G\n" +
	"\x16GetUserByUserIdRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"'\n" +
	"\x0fGetUsersRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\"[\n" +
	"\x15GetSortedUsersRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x16\n" +
	"\x06sorter\x18\x02 \x01(\tR\x06sorter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xe0\x01\n" +
	"\x19GetPaginationUsersRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12B\n" +
	"\x05query\x18\x04 \x03(\v2,.api.v1.GetPaginationUsersRequest.QueryEntryR\x05query\x1a8\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x13GetUserCountRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x1b\n" +
	"\tis_online\x18\x02 \x01(\tR\bisOnline\"\x96\x01\n" +
	"\x12SetPasswordRequest\x12\x1d\n" +
	"\n" +
	"user_owner\x18\x01 \x01(\tR\tuserOwner\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12!\n" +
	"\fold_password\x18\x03 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x04 \x01(\tR\vnewPassword\"2\n" +
	"\x0eAddUserRequest\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.api.v1.UserR\x04user\"O\n" +
	"\x11UpdateUserRequest\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.api.v1.UserR\x04user\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\"5\n" +
	"\x11DeleteUserRequest\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.api.v1.UserR\x04user\"<\n" +
	"\x18CheckUserPasswordRequest\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.api.v1.UserR\x04user\"\x1e\n" +
	"\fBoolResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"0\n" +
	"\fUserResponse\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.api.v1.UserR\x04user\"3\n" +
	"\rUsersResponse\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.api.v1.UserR\x05users\"]\n" +
	"\x16PaginatedUsersResponse\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.api.v1.UserR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"%\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count2\x83\a\n" +
	"\vUserService\x127\n" +
	"\aGetUser\x12\x16.api.v1.GetUserRequest\x1a\x14.api.v1.UserResponse\x12E\n" +
	"\x0eGetUserByEmail\x12\x1d.api.v1.GetUserByEmailRequest\x1a\x14.api.v1.UserResponse\x12E\n" +
	"\x0eGetUserByPhone\x12\x1d.api.v1.GetUserByPhoneRequest\x1a\x14.api.v1.UserResponse\x12G\n" +
	"\x0fGetUserByUserId\x12\x1e.api.v1.GetUserByUserIdRequest\x1a\x14.api.v1.UserResponse\x12:\n" +
	"\bGetUsers\x12\x17.api.v1.GetUsersRequest\x1a\x15.api.v1.UsersResponse\x12F\n" +
	"\x0eGetSortedUsers\x12\x1d.api.v1.GetSortedUsersRequest\x1a\x15.api.v1.UsersResponse\x12W\n" +
	"\x12GetPaginationUsers\x12!.api.v1.GetPaginationUsersRequest\x1a\x1e.api.v1.PaginatedUsersResponse\x12B\n" +
	"\fGetUserCount\x12\x1b.api.v1.GetUserCountRequest\x1a\x15.api.v1.CountResponse\x127\n" +
	"\aAddUser\x12\x16.api.v1.AddUserRequest\x1a\x14.api.v1.BoolResponse\x12=\n" +
	"\n" +
	"UpdateUser\x12\x19.api.v1.UpdateUserRequest\x1a\x14.api.v1.BoolResponse\x12=\n" +
	"\n" +
	"DeleteUser\x12\x19.api.v1.DeleteUserRequest\x1a\x14.api.v1.BoolResponse\x12?\n" +
	"\vSetPassword\x12\x1a.api.v1.SetPasswordRequest\x1a\x14.api.v1.BoolResponse\x12K\n" +
	"\x11CheckUserPassword\x12 .api.v1.CheckUserPasswordRequest\x1a\x14.api.v1.BoolResponseB\n" +
	"Z\b../protob\x06proto3"

var (
	file_api_v1_user_proto_rawDescOnce sync.Once
	file_api_v1_user_proto_rawDescData []byte
)

func file_api_v1_user_proto_rawDescGZIP() []byte {
	file_api_v1_user_proto_rawDescOnce.Do(func() {
		file_api_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_user_proto_rawDesc), len(file_api_v1_user_proto_rawDesc)))
	})
	return file_api_v1_user_proto_rawDescData
}

var file_api_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_v1_user_proto_goTypes = []any{
	(*ManagedAccount)(nil),            // 0: api.v1.ManagedAccount
	(*User)(nil),                      // 1: api.v1.User
	(*GetUserRequest)(nil),            // 2: api.v1.GetUserRequest
	(*GetUserByEmailRequest)(nil),     // 3: api.v1.GetUserByEmailRequest
	(*GetUserByPhoneRequest)(nil),     // 4: api.v1.GetUserByPhoneRequest
	(*GetUserByUserIdRequest)(nil),    // 5: api.v1.GetUserByUserIdRequest
	(*GetUsersRequest)(nil),           // 6: api.v1.GetUsersRequest
	(*GetSortedUsersRequest)(nil),     // 7: api.v1.GetSortedUsersRequest
	(*GetPaginationUsersRequest)(nil), // 8: api.v1.GetPaginationUsersRequest
	(*GetUserCountRequest)(nil),       // 9: api.v1.GetUserCountRequest
	(*SetPasswordRequest)(nil),        // 10: api.v1.SetPasswordRequest
	(*AddUserRequest)(nil),            // 11: api.v1.AddUserRequest
	(*UpdateUserRequest)(nil),         // 12: api.v1.UpdateUserRequest
	(*DeleteUserRequest)(nil),         // 13: api.v1.DeleteUserRequest
	(*CheckUserPasswordRequest)(nil),  // 14: api.v1.CheckUserPasswordRequest
	(*BoolResponse)(nil),              // 15: api.v1.BoolResponse
	(*UserResponse)(nil),              // 16: api.v1.UserResponse
	(*UsersResponse)(nil),             // 17: api.v1.UsersResponse
	(*PaginatedUsersResponse)(nil),    // 18: api.v1.PaginatedUsersResponse
	(*CountResponse)(nil),             // 19: api.v1.CountResponse
	nil,                               // 20: api.v1.User.PropertiesEntry
	nil,                               // 21: api.v1.GetPaginationUsersRequest.QueryEntry
}
var file_api_v1_user_proto_depIdxs = []int32{
	20, // 0: api.v1.User.properties:type_name -> api.v1.User.PropertiesEntry
	0,  // 1: api.v1.User.managed_accounts:type_name -> api.v1.ManagedAccount
	21, // 2: api.v1.GetPaginationUsersRequest.query:type_name -> api.v1.GetPaginationUsersRequest.QueryEntry
	1,  // 3: api.v1.AddUserRequest.user:type_name -> api.v1.User
	1,  // 4: api.v1.UpdateUserRequest.user:type_name -> api.v1.User
	1,  // 5: api.v1.DeleteUserRequest.user:type_name -> api.v1.User
	1,  // 6: api.v1.CheckUserPasswordRequest.user:type_name -> api.v1.User
	1,  // 7: api.v1.UserResponse.user:type_name -> api.v1.User
	1,  // 8: api.v1.UsersResponse.users:type_name -> api.v1.User
	1,  // 9: api.v1.PaginatedUsersResponse.users:type_name -> api.v1.User
	2,  // 10: api.v1.UserService.GetUser:input_type -> api.v1.GetUserRequest
	3,  // 11: api.v1.UserService.GetUserByEmail:input_type -> api.v1.GetUserByEmailRequest
	4,  // 12: api.v1.UserService.GetUserByPhone:input_type -> api.v1.GetUserByPhoneRequest
	5,  // 13: api.v1.UserService.GetUserByUserId:input_type -> api.v1.GetUserByUserIdRequest
	6,  // 14: api.v1.UserService.GetUsers:input_type -> api.v1.GetUsersRequest
	7,  // 15: api.v1.UserService.GetSortedUsers:input_type -> api.v1.GetSortedUsersRequest
	8,  // 16: api.v1.UserService.GetPaginationUsers:input_type -> api.v1.GetPaginationUsersRequest
	9,  // 17: api.v1.UserService.GetUserCount:input_type -> api.v1.GetUserCountRequest
	11, // 18: api.v1.UserService.AddUser:input_type -> api.v1.AddUserRequest
	12, // 19: api.v1.UserService.UpdateUser:input_type -> api.v1.UpdateUserRequest
	13, // 20: api.v1.UserService.DeleteUser:input_type -> api.v1.DeleteUserRequest
	10, // 21: api.v1.UserService.SetPassword:input_type -> api.v1.SetPasswordRequest
	14, // 22: api.v1.UserService.CheckUserPassword:input_type -> api.v1.CheckUserPasswordRequest
	16, // 23: api.v1.UserService.GetUser:output_type -> api.v1.UserResponse
	16, // 24: api.v1.UserService.GetUserByEmail:output_type -> api.v1.UserResponse
	16, // 25: api.v1.UserService.GetUserByPhone:output_type -> api.v1.UserResponse
	16, // 26: api.v1.UserService.GetUserByUserId:output_type -> api.v1.UserResponse
	17, // 27: api.v1.UserService.GetUsers:output_type -> api.v1.UsersResponse
	17, // 28: api.v1.UserService.GetSortedUsers:output_type -> api.v1.UsersResponse
	18, // 29: api.v1.UserService.GetPaginationUsers:output_type -> api.v1.PaginatedUsersResponse
	19, // 30: api.v1.UserService.GetUserCount:output_type -> api.v1.CountResponse
	15, // 31: api.v1.UserService.AddUser:output_type -> api.v1.BoolResponse
	15, // 32: api.v1.UserService.UpdateUser:output_type -> api.v1.BoolResponse
	15, // 33: api.v1.UserService.DeleteUser:output_type -> api.v1.BoolResponse
	15, // 34: api.v1.UserService.SetPassword:output_type -> api.v1.BoolResponse
	15, // 35: api.v1.UserService.CheckUserPassword:output_type -> api.v1.BoolResponse
	23, // [23:36] is the sub-list for method output_type
	10, // [10:23] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_v1_user_proto_init() }
func file_api_v1_user_proto_init() {
	if File_api_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_user_proto_rawDesc), len(file_api_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_user_proto_goTypes,
		DependencyIndexes: file_api_v1_user_proto_depIdxs,
		MessageInfos:      file_api_v1_user_proto_msgTypes,
	}.Build()
	File_api_v1_user_proto = out.File
	file_api_v1_user_proto_goTypes = nil
	file_api_v1_user_proto_depIdxs = nil
}
